### PR TITLE
[REF] git: Add a link of video 'how to' in README file

### PR DESCRIPTION
**Pull request by moylop260**
I created a video of how to configurate `git hook` in your local environment.
I can to share it in this repository.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Thanks for the initiative, but seeing the video, I think it's not so helpful, because you make a lot of operations and there's no indication on what is being done and newcomers are going to be lost the same.

**Comment by moylop260** [comment]
@pedrobaeza 
Yes you are done!
asciinema allow it copy&paste command of video but don't have graphics and don't have audio.

However, the guion is in README file.
Just README or jus video is confusing to newcomers.

IMHO README plus video is less confusing.

**Comment by pedrobaeza** [comment]
OK, let's see what others think

**Comment by nhomar** [comment]
2015-08-06 11:34 GMT-05:00 moylop260 <notifications@github.com>:

> However, the guion is in README file.
> Just README or jus video is confusing to newcomers
>

@moylop260

The video make some mistakes in the middle and really it is a little
confusing.

Then the issue is not "Video or not Video" the issue is that "The video is
not good enought".

If we will add a video without audio (which I am agreed because asciicinema
is great) this must be really straight forward with what it does...

No change of tabs or errors in cd's allowed there.

And for step by step you can write in the shell it self....

- In the video something likw:

$ What you will do ^C
$ Step 1 enter
$ Step 2 enter.
$ COmment about what you did ^C
$ Step 3 enter.
$ Comment about what you See and what receive.

Any other things on your shell can confuse the reader, well, like
@pedroBaeza this video the first 20 seconds confuse me also.

Regards.

-- 
--------------------
Saludos Cordiales

CEO at Vauxoo <https://www.vauxoo.com> Odoo's Gold Partner.

[image: --]
Nhomar Hernandez
[image: http://]about.me/nhomar
<http://about.me/nhomar?promo=email_sig>

**Comment by dreispt** [comment]
Maybe I'm getting old, but I saw it for 30 seconds and was totally lost on what was going on...

**Comment by yvaucher** [comment]
@moylop260 It's a good initiative and I also agree with @nhomar that to improve it you need to start by telling what the watcher will see.

**Pull request closed without merging**
