### PR TITLE
Clone oca_dependencies from OCA owner. Fixes #274

### LINKED ISSUE #274: Error cloning oca_dependencies
TravisCI tests fail to clone the OCA dependencies, with the message `remote: Invalid username or password.` and [traceback](https://travis-ci.org/dreispt/project-service/jobs/85292191#L170):

snap 2015-10-14 at 13 21 39

I notice that the clone is being done for the  `dreispt` user instead of `OCA`,
BTW it would also be advisable for the repo URL to end with `.git`.

### PR DESCRIPTION
**Pull request by dreispt**

### CODE REVIEW

**Comment by moylop260** [comment]
LGTM (without test)
Could use this pr in your other one to test it?

**Comment by yvaucher** [comment]
:+1:

**Comment by pedrobaeza** [comment]
:+1:

This way, we get a consistent behavior in oca_dependencies.txt over forked repositories

**Comment by dreispt** [comment]
Can this be merged?

**Comment by dreispt** [comment]
The self-tests should have catched the failing oca_dependencies cloning. I'll have to dig into that.

**Comment by dreispt** [comment]
Looks like I removed those self-tests here: https://github.com/OCA/maintainer-quality-tools/commit/0a324cdd47c03c90e27c0cd6baaf7d5a17174404
I'll work on a way to bet them back onboard.

**Pull request merged**
