### PR TITLE
[REF] test_server: Add method to run commands from environment variables

### PR DESCRIPTION
**Pull request by moylop260**
- To run custom script from other sources. (by example: runbot with travis2docker)

### CODE REVIEW

**Comment by moylop260** [comment]
This PR replace done [follow change](https://github.com/vauxoo-dev/maintainer-quality-tools/commit/4b208d6ecaf2cabafa66ef16e19206310a304e1f
) refused by @guewen:

Now, runbot is running correctly using OCA/MQT and travis2docker of a way generic:
https://travis-ci.org/OCA/runbot-addons/jobs/96920438

**Comment by moylop260** [comment]
@all feedback is welcome

**Comment by moylop260** [comment]
ping

**Comment by oscarolar** [comment]
:+1:

**Comment by osvalr** [comment]
:+1:

**Comment by alan196** [comment]
+1

**Pull request merged**
