### PR TITLE
On TravisCI stop alive process to get green builds

### PR DESCRIPTION
**Pull request by dreispt**

### CODE REVIEW

**Comment by dreispt** [comment]
@moylop260 Can you check if this fix suits you?

**Comment by moylop260** [comment]
This is a good solution to me.
Thanks

Just we need test this parameter from runbot.
Could you create a dummy PR to any green oca project to use this branch?

**Comment by dreispt** [comment]
> Just we need test this parameter from runbot.

It already is.

> Could you create a dummy PR to any green oca project to use this branch?

I don't see the point: the issue is only with MQT self tests.

**Comment by dreispt** [comment]
This PR is just about fixing the self-tests to the INSTANCE_ALIVE feature, so that we can get green CI builds again.

**Pull request merged**
