### PR TITLE
[IMP] Allow to filter on applications or filter out l10n modules

### PR DESCRIPTION
**Pull request by StefanRijnhart**
This allows to select or exclude modules marked as applications plus their dependencies, and to select or exclude localization modules.

https://github.com/OCA/OCB/issues/639
https://github.com/OCA/OCB/pull/722

### CODE REVIEW

**Comment by mreficent** [comment]
I have a PR for you https://github.com/StefanRijnhart/maintainer-quality-tools/pull/1. 😉

**Comment by pedrobaeza** [comment]
Travis is red

**Comment by StefanRijnhart** [comment]
I won't have time to work in this in the next couple of days so if you want to open your own PR @mreficent and close this one it's fine.

**Comment by mreficent** [comment]
@StefanRijnhart Ok, I will try.

PR superseeded by https://github.com/OCA/maintainer-quality-tools/pull/537.

**Pull request closed without merging**
