### PR TITLE
use sudo to install less

### PR DESCRIPTION
**Pull request by GSLabIt**
fix installation using github actions, see #666

### CODE REVIEW

**Comment by pedrobaeza** [comment]
You mustn't use sudo or Travis will put the builds outside Docker containers in slower machines, so you need to find other way.

**Comment by GSLabIt** [comment]
@pedrobaeza ah ok ..any hint on how to fix?

**Comment by pedrobaeza** [comment]
Sorry, no, but use Travis or your fork of MQT with GH actions

**Comment by GSLabIt** [comment]
@pedrobaeza ok thanks, will close this PR.

**Comment by fuentes010** [comment]
Hi @GSLabIt, We are using MQT in our GH actions without any issue.
https://hub.docker.com/r/studio73/gha-oca-mqt

```
jobs:
  test:
    runs-on: ubuntu-latest
    container: studio73/gha-oca-mqt:12.0
    steps:
      ...
      - name: testing
        env:
          PGHOST: postgres
          PGUSER: odoo
          PGPASSWORD: postgres_pswd
          PGPORT: 5432
        run: |
          . setup_oca_mqt
          travis_run_tests

```

**Comment by GSLabIt** [comment]
@fuentes010 thanks, may i use it? I've forked and trying to build image on doker hub but it keep failing because of: 
```
COPY bin/* /usr/local/bin/
COPY failed: no source files were specified
```

**Comment by fuentes010** [comment]
> @fuentes010 thanks, may i use it? I've forked and trying to build image on doker hub but it keep failing because of:
> 
> ```
> COPY bin/* /usr/local/bin/
> COPY failed: no source files were specified
> ```

You have to build the image being at the root of the repo using:
`docker build -f VERSION/Dockerfile . -t gha-oca-mqt:VERSION`

Anyways you don't need to build the image is already built and available at Docker hub `studio73/gha-oca-mqt:12.0`
In the previous comment you have an example how to use the image in your GH action workflow.

* Python2 `studio73/gha-oca-mqt:10.0`: Works for 8.0, 9.0 and 10.0
* Python3 `studio73/gha-oca-mqt:12.0`: Works for 11.0, 12.0 and 13.0

We've planned to change the tags to something like `py2` and `py3` but is not a priority

If you need any help let me know.

**Comment by GSLabIt** [comment]
@fuentes010 any hint on how to clone private repos set in oca_dependency?

**Comment by fuentes010** [comment]
You have to set the repo url after the repo name
[Here](https://github.com/OCA/maintainer-quality-tools/blob/master/travis/clone_oca_dependencies#L20-L26) you can see  the oca_dependencies.txt file structure
```
...
my-private-repo git@github.com:my-org/my-private-repo.git
web
website
...
```


If you add comments like `#merges REPO PR_NUMBER` `setup_oca_mqt` will try to aggregate PRs using this [script](https://github.com/Studio73/gha-oca-mqt/blob/master/bin/merge_prs) 

Next configuration will aggregate PR 111 and 112 to the web repository if there is no conflict
```
...
my-private-repo git@github.com:my-org/my-private-repo.git
web
#merges web 111,112
website
...
```

**Comment by GSLabIt** [comment]
@fuentes010 thx for the quick answer. I did this:
> ...
> my-private-repo git@github.com:my-org/my-private-repo.git
> web
> website
> ...

but keep getting an error:

```
Warning: Permanently added the RSA host key for IP address '140.82.113.4' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.
Please make sure you have the correct access rights and the repository exists.
Traceback (most recent call last):
File "/github/home/maintainer-quality-tools/travis/clone_oca_dependencies", line 136, in <module> run(deps_checkout_dir, build_dir)
File "/github/home/maintainer-quality-tools/travis/clone_oca_dependencies", line 111, in run 
url, branch, commit)
File "/github/home/maintainer-quality-tools/travis/clone_oca_dependencies", line 74, in git_checkout subprocess.check_call(command)
File "/usr/local/lib/python3.6/subprocess.py", line 311, in check_call
 raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['git', 'clone', '-q', 'git@github.com:ooops404/ooops-release.git', '-b', '12.0', '--single-branch', '--depth=1', '/github/home/dependencies/ooops-release']' returned non-zero exit status 128.
```
It seems like docker ssh-key needs to be added to github ssh keys, isn't it?

**Comment by fuentes010** [comment]
Yes, you have to configure a valid ssh key inside your GH action.

**Comment by GSLabIt** [comment]
> Yes, you have to configure a valid ssh key inside your GH action.

THx for the hint, you mean as ENV param?

**Pull request closed without merging**
