### PR TITLE
[REF] enable new beta checks of pylint 1.3.2

### PR DESCRIPTION
**Pull request by moylop260**
Enable just for pull request in modules changes the following checks:
 - consider-merging-classes-inherited
 - dangerous-view-replace-wo-priority
 - file-not-used
 - odoo-addons-relative-import
 - old-api7-method-defined (for >=v8)

### CODE REVIEW

**Comment by pedrobaeza** [comment]
:+1:

**Comment by rvalyi** [comment]
:+1: and thanks for the hard work (in pylint-odoo I mean)

**Comment by osvalr** [comment]
:+1:

**Comment by pedrobaeza** [comment]
New checks incoming!

**Pull request merged**
