### PR TITLE
[REF] pylint_beta.cfg: Add deprecated module in beta messages

### PR DESCRIPTION
**Pull request by moylop260**
Disable error [W0402(deprecated-module), ] Uses of a deprecated module 'openerp.osv'
Now show warning beta message

This PR fix the thread "Maintainer-quality-tools multiple quick changes" sent to contributors email.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Is this for solving current issue?

**Comment by moylop260** [comment]
@pedrobaeza 
Yep, I'm waiting travis because we need to know new expected errors... let me see...

**Comment by moylop260** [comment]
FYI this PR fix the thread "Maintainer-quality-tools multiple quick changes" sent to `contributors` email.

**Comment by moylop260** [comment]
Travis is too slow now.
FYI I ran with travis2docker and changed the expected errors values.

**Comment by dreispt** [comment]
@moylop260 You might want to also add `orm.Model` to the deprecated list. It was the 7.0 correct way, and I have found it in several modules.

**Comment by moylop260** [comment]
> @moylop260 You might want to also add orm.Model to the deprecated list. It was the 7.0 correct way, and I have found it in several modules.

IMHO this PR is just to fix the thread "Maintainer-quality-tools multiple quick changes" sent to contributors email.
But you have a good point... I have created a entry in [ToDo enables](https://github.com/OCA/maintainer-quality-tools/issues/252) because I need to add test case, expected error, pylint_*.cfg changes...

**Comment by JonathanNEMRY** [comment]
:+1:  thanks for this quick-fix @moylop260

**Comment by pedrobaeza** [comment]
:+1:

**Comment by pedrobaeza** [comment]
Fast-tracking for solving this

**Comment by charbeljc** [comment]
thanks you @moylop260, having a warning remainder for the migration to be donne, but with green travis status during migration work is a good thing.

**Pull request merged**
