### PR TITLE
[IMP] Remove pylint beta messages from PR cfg file

### PR DESCRIPTION
**Pull request by Yajo**
This way we DRY the files and also allow the PR cfg file to be used in standalone mode.

@Tecnativa

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Travis is failing

**Comment by Yajo** [comment]
Let's see now.

**Comment by Yajo** [comment]
Yep, 💚

**Comment by pedrobaeza** [comment]
I understand that no check is removed. You only concatenate both - PR and normal -, isn't it?

**Comment by Yajo** [comment]
Actually normal + beta, or pr + beta if I'm not wrong. @moylop260 should know it better.

**Comment by moylop260** [comment]
Hello @Yajo 

normal.cfg + pr.cfg - beta messages for PRs
normal.cfg - beta messages for stable branches

I mean, beta messages are not considered for affecting the status build result from final result.

Example:
normal.cfg enables:
 - check1
 - check2

pr.cfg enables:
 - check3
 - check4

beta.cfg enables:
  - check1
  - check4

If a PR or stable branch emit the messages `check1` or/and `check4` then will be result green because are beta messages (these checks are not approval 100% yet)

If a PR or stable branch emit the message `check2` and/or `check3` then will be result red because are not silent from beta message.

Note: If you have a better solution for this feature is welcome.
Thanks!

**Comment by Yajo** [comment]
AFAIK the better solution is this PR, isn't it?

What it does is unduplicate checks from beta cfg file, and add them manually through CLI.

This way, behavior should remain the same while PR cfg can be used in standalone mode (by not including beta checks)

**Pull request merged**
