### PR TITLE
Fix error when VERSION is master. Fixes #398

### LINKED ISSUE #398: ValueError: could not convert string to float: master
Steps to reproduce it:
1. Assign environment variable `VERSION="master"` in a .travis.yml
2. Wait travis build

Result:
`ValueError: could not convert string to float: master`

Expected:
Working fine like as other version of odoo/odoo

### PR DESCRIPTION
**Pull request by dreispt**
This alternative to the fix provided by #409. IMO this is simpler and not intrusive on the code used to run the tests.

### CODE REVIEW

**Comment by moylop260** [comment]
I prefer to use the concluded solution from https://github.com/OCA/maintainer-quality-tools/issues/398 by other contributors where you have a comment too

**Comment by blaggacao** [comment]
Can we produce a conclusion, here? I'm not 100% convinced that it would be worthwhile to invest time and effort to get this sorted out. My suggestion is @dreispt to step back on this, and look how #411 behaves on production (like in opportunistic merging), we can put a big question mark on it, so if it needs to be reversed, then referencing this question mark, could provoke a rather swift fix on this, without the need to repeat this discussion, would that be ok? I'd like to push other topics, too, and being blocked on this consumes focus.

**Comment by blaggacao** [comment]
@dreispt Can I stress again on moving forward on #411 please? I could not reliably follow the line of thought of what's the specific benefit of this blocking here?
Since when mere preferences becoming hurdle objections does foster collaboration?

**Comment by dreispt** [comment]
I agree that this fix has strong limitations, so I'm closing this.
But I still disagree that renaming the Odoo startup script file is the proper solution.
A good solution could be to inspect if `odoo.py` exists, and if not use `openerp.py`.

**Pull request closed without merging**
