### PR TITLE
[DOC] on different testing environments

### PR DESCRIPTION
**Pull request by blaggacao**
Resulting of https://github.com/OCA/maintainer-quality-tools/pull/392#issuecomment-271409121 this is an attempt to open up this greate set of tools for a broader user base.

### CODE REVIEW

**Comment by blaggacao** [comment]
As talked about on https://github.com/OCA/maintainer-quality-tools/pull/392#issuecomment-271409121

**Comment by blaggacao** [comment]
@jcdrubay I know you are keen on this 💃

**Comment by jcdrubay** [comment]
@blaggacao Hi, I am indeed keen on this. Yet, at this time my focus is on vertical-medical. I ll get back to maintainers-quality-tools soon.

**Comment by blaggacao** [comment]
@dreispt Hi Daniel, I would like to include my findings here. I'm sure they will be quite helpful to other people who are about to explore MQT but not with the OCA use case as the only use case in mind. All gotchas of 2 days work are included and highlighted, so I guess it's a valuable piece of documentation. Could you ask you a review? 😉

**Comment by jcdrubay** [comment]
Thanks for your effort on documenting, during my attempts to contribute I felt a bit lost and it surely would have helped. Now I am scared of getting back to this repo as it is quite complicated and not so easy to know what Travis will give you before you push the code. I think more documentation for contributors would help :)

In case this help, I had also added some ideas to test locally here: https://github.com/OCA/maintainer-quality-tools/pull/380#issuecomment-259624615

**Comment by jcdrubay** [comment]
Thanks @blaggacao  for your effort on documenting, during my attempts to contribute I felt a bit lost and it surely would have helped. Now I am scared of getting back to this repo as it is quite complicated and not so easy to know what Travis will give you before you push the code. I also think more documentation for contributors would help a lot :)

In case this help, I had also added some ideas to test locally here: https://github.com/OCA/maintainer-quality-tools/pull/380#issuecomment-259624615

**Comment by dreispt** [comment]
@jcdrubay please don't be afraid to play with this repo. 
Indeed it is complicated right now, but in the end of the day PRs are a safe playground.
My advice is to keep changesets as small as possible, so that changes are less risky, reviews are easier to do, and you don't loose too much time if going in the wrong direction.

**Comment by blaggacao** [comment]
@jcdrubay Good news is that maintainers are very open for improvement 😃 FYI, I'll take on the pylint issues in the following days. As we want to take advantage of the upcoming migration to version 11 to make all our stuff fully OCA compliant... From there it would be interesting to learn, what additional checks can we include in odoo-pylint as a very valuable tool to train new team members (by trial and error) on Odoo idioms...

**Pull request closed without merging**
