### PR TITLE
[ADD] odoolint: Add runtime lint checks

### PR DESCRIPTION
**Pull request by moylop260**
This module is result of the following [previous discuss](https://github.com/OCA/maintainer-quality-tools/issues/331) and https://github.com/OCA/server-tools/pull/444

TODO: 
- [ ] How to manage different versions of odoolint module
- [ ] PR for MQT to process the warning messages
- [ ] Migrate it to version 9.0
- [ ] Avoid install it in 6.1

### CODE REVIEW

**Comment by pedrobaeza** [comment]
I think we can create special branches for this tool: odoolint-8.0, odoolint-9.0...

**Comment by moylop260** [comment]
@pedrobaeza 
Thanks for feedback

**Comment by moylop260** [comment]
FYI I ran some projects to test this PR...
 - https://github.com/OCA/rma/pull/91
  - Ran without warnings.
 - https://github.com/OCA/l10n-argentina/pull/38
  - Ran with old errors
 - https://github.com/OCA/l10n-spain/pull/370
  - Ran with warning [The xml_id 'base_vat.view_partner_form' is unreachable](https://travis-ci.org/OCA/l10n-spain/jobs/136985885#L1358-L1359). In order to discard a false warning I ran `~/odoo-8.0/odoo.py -i l10n_es_aeat_mod216` and I saw the following error:
screen shot 2016-06-11 at 6 15 47 pm

The conclusion is that this check is working and It will help us to detect this common issues early.

@pedrobaeza Is this a known issue in l10n-spain?

**Comment by nhomar** [comment]
@moylop260 I think this PR can be closed because this was moved to another repository right?

**Comment by moylop260** [comment]
@pedrobaeza @yajo
this is the module of dynamic checks.
The last talk was create a new project to manage just this type of modules

**Comment by pedrobaeza** [comment]
Yeah, that's it. But we haven't decided how to call it, structure it and so on.

**Pull request closed without merging**
