### PR TITLE
[REF] pylint_beta.cfg: Enable manifest's checks as stable ones (Affect build status)

### PR DESCRIPTION
**Pull request by moylop260**
- Fix https://github.com/OCA/maintainer-quality-tools/issues/443
  - The error is emitted but as beta:
    - `l10n_th_address/__manifest__.py:4: [C8101(manifest-required-author), ] Missing author required "Odoo Community Association (OCA)" in manifest file`:
       - https://travis-ci.org/OCA/l10n-thailand/jobs/228809869#L514

This PR remove these checks from beta in order to affect build result.

FOR MERGER
==========

Please, merge and squash from github button

### CODE REVIEW

**Comment by sbidoul** [comment]
Thanks a lot @moylop260. 

Ok for author (OCA must be there) and `manifest-required-key` (ie license, we must not publish to apps.odoo.com without license).

Regarding `manifest-deprecated-key` (description, active) perhaps it better to keep it in beta until v11?

**Comment by dreispt** [comment]
Travis is red... and AFAICT it will be a pain to fix it.
We need to somehow convert MQT tests into UnitTest packages (/rant).

**Comment by moylop260** [comment]
@dreispt Like as https://github.com/OCA/maintainer-quality-tools/pull/434?

**Comment by dreispt** [comment]
We should make an announcement on the Contributors ML before merging this.

**Comment by pedrobaeza** [comment]
Any news on this?

**Comment by moylop260** [comment]
I just fixed conflicts

**Comment by pedrobaeza** [comment]
@dreispt @sbidoul any objection?

**Comment by pedrobaeza** [comment]
OK, as I see the previous approval from @dreispt, I merge.

**Pull request merged**
