### PR TITLE
[UPD] makepot: add 14.0 and 15.0 support

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Please! :)

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]
Ouch, this is very heavy that we are without POT generation. I didn't know this is by branches. Please add 16.0, 17.0 and 18.0 in advance for avoiding this problem in the future.

**Comment by AaronHForgeFlow** [comment]
wtf

**Comment by MiquelRForgeFlow** [comment]
@pedrobaeza checks are green

**Comment by pedrobaeza** [comment]
Not sure if this needs to be deployed somewhere. Maybe with GH actions is not needed? cc @sbidoul

**Comment by sbidoul** [comment]
There is `or "ocabot-merge" in os.environ.get('TRAVIS_BRANCH', '')`

So .pot are generated when merging with the bot, right ?

**Comment by pedrobaeza** [comment]
I can't really say... @MiquelRForgeFlow you have got to this due to something missing that traces back to here?

**Comment by sbidoul** [comment]
In think the only "problem" is that .pot files are not regenerated nightly on the 14.0 and 15.0 branches.

When merging with the bot, they are generated on merge both with Travis and GitHub actions.

**Comment by pedrobaeza** [comment]
And with bot, all POT files are regenerated, or only of the affected modules?

**Pull request merged**
