### PR TITLE
[IMP] pylint: Enable check to verify version format in manifest file

### PR DESCRIPTION
**Pull request by lescobarvx**
[IMP] pylint: Enable check to verify version format in manifest file

### CODE REVIEW

**Comment by lescobarvx** [comment]
This PR depends on PR of pylint_odoo: https://github.com/OCA/pylint-odoo/pull/18

**Comment by pedrobaeza** [comment]
Thanks for this! :+1: 

I think we should bump the version in pylint_odoo lib and put here in the requirements.txt.

**Comment by max3903** [comment]
:+1:

**Comment by atchuthan** [comment]
This would be helpful for new OCA contributors :+1:

**Pull request merged**
