### PR TITLE
Let prettier indent XML files

### LINKED ISSUE #632: No so pretty XML formatting by prettier
Example on mis_builder/report/mis_report_instance_qweb.xml

image

@yajo WDYT ?

### PR DESCRIPTION
**Pull request by sbidoul**
fixes #632

### CODE REVIEW

**Comment by Yajo** [comment]
Do you have a sample PR or diff to check the effect?

**Comment by sbidoul** [comment]
> I'd like xmlSelfClosingSpace=true but that's another story

@simahawk ok, no big deal for me, I reverted that commit.

**Comment by sbidoul** [comment]
> Do you have a sample PR or diff to check the effect?

I opened https://github.com/OCA/web/pull/1540

**Comment by simahawk** [comment]
@sbidoul the OCA/web PR got merged: shall we merge here?

**Pull request merged**
