### PR TITLE
[REF] disable license OEEL-1 for oca projects

### PR DESCRIPTION
**Pull request by moylop260**
https://github.com/OCA/pylint-odoo/pull/165#issuecomment-339806489

### CODE REVIEW

**Comment by sbidoul** [comment]
:+1: Travis is red though.

**Comment by moylop260** [comment]
The red is unrelated since the direct commit (without PR) https://github.com/OCA/maintainer-quality-tools/commit/27792ba2e1e95212c1a0670784bdd3cd1a5b33c0 added the following flake8 error:
 - [./travis/travis_transifex.py:12:1: E402 module level import not at top of file](https://travis-ci.org/OCA/maintainer-quality-tools/jobs/289684494#L873)

**Comment by pedrobaeza** [comment]
I will fix it later, sorry.

**Comment by dreispt** [comment]
I thought there were no direct commits on OCA repos 😞

**Comment by pedrobaeza** [comment]
That was because all 11.0 branches were red

**Pull request merged**
