### PR TITLE
Avoid setuptools 50

### PR DESCRIPTION
**Pull request by sbidoul**
This may fix our runbot issues.

### CODE REVIEW

**Review by yvaucher — APPROVED** [review]
Waiting for travis result but LGTM

**Review by gurneyalex — APPROVED** [review]
can't harm

**Review by bealdav — APPROVED** [review]

**Comment by legalsylvain** [comment]
thanks a lot !

**Comment by remi-filament** [comment]
FYI Issue is fixed with setuptools version 50.0.3, I tested it this morning

**Comment by sbidoul** [comment]
@remi-filament thanks for the update. I reverted the workaround.

**Pull request merged**
