### PR TITLE
Don't run tests on Odoo master branch

### PR DESCRIPTION
**Pull request by dreispt**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
:+1:

**Comment by dreispt** [comment]
Looking again, that line is the only one testing the EXCLUDE directive.
Maybe I rather switch `master` to `8.0` instead of removing the line...

**Comment by bwrsandman** [comment]
This needs to be rebased/redone. @dreispt have you decieded on removing or switching?

**Comment by dreispt** [comment]
I'll work on this.

**Comment by gurneyalex** [comment]
:+1:

**Pull request merged**
