### PR TITLE
[IMP] Adapt .editorconfig

### LINKED ISSUE #614: Autopush .editorconfig to repos
Hi there!

First, a little bit of background:

- After https://github.com/OCA/maintainer-quality-tools/pull/613 was merged now we have a valid `.editorconfig` file: https://github.com/OCA/maintainer-quality-tools/blob/7190b984e4fc96216d667885aeaf9c84bae0ca52/sample_files/.editorconfig#L1-L30

- According to what @sbidoul said in https://github.com/OCA/maintainer-quality-tools/pull/613#issuecomment-537885747, all other new pre-commit files are autopushed to chosen module repo branches by the bot.

- The `.editorconfig` file was skipped because it wasn't announced nor discussed with the community before, as explained in https://github.com/OCA/maintainer-quality-tools/pull/613#issuecomment-541092172.

Well, here we are :grin:, let's discuss it. Should we push that file also to repos? If so, how? Is it a matter of just putting it in the pre-commit-13.0 folder? Otherwise having it there is useless... :roll_eyes: 

You can read what it's for in https://editorconfig.org, and how we came to it in https://github.com/acsone/maintainer-quality-tools/pull/1.

Thanks!

### PR DESCRIPTION
**Pull request by Yajo**
Fix #614.

### CODE REVIEW

**Comment by Yajo** [comment]
@sbidoul Should I move the file to other folder for it to be pushed to repos?

**Comment by sbidoul** [comment]
Thanks!

> Should I move the file to other folder for it to be pushed to repos?

This will probably have a different lifecycle than the pre-commit configs, so better leave it separate for now.

**Comment by sbidoul** [comment]
I'll push when the ci-skip addon is installed on runbot

**Comment by Yajo** [comment]
I added support for `.eslintrc` and `*.json` using 2 spaces.

Can we merge now?

**Comment by pedrobaeza** [comment]
@sbidoul ?

**Comment by sbidoul** [comment]
Yes, LGTM. I can push tonight with a `[ci skip]`.

**Pull request merged**
