### PR TITLE
[FIX] travis_install_nightly: Freeze flake8 version

### LINKED ISSUE #496: New check appears "magically": E722 do not use bare except
Example: https://travis-ci.org/OCA/OpenUpgrade/builds/291659303#L562

It can be because of a new flake8 version. 

@moylop260 any clue?

### PR DESCRIPTION
**Pull request by pedrobaeza**
Closes #496 

@Tecnativa

### CODE REVIEW

**Comment by pedrobaeza** [comment]
I'm afraid this hasn't been enough. In other place the newest version is still installed/upgraded. Any idea?

**Comment by moylop260** [comment]
Do you have a recent build with this case?

**Comment by pedrobaeza** [comment]
This one is an example:

https://travis-ci.org/OCA/OpenUpgrade/builds/292775509

**Comment by pedrobaeza** [comment]
Sorry, that example is bad, because OpenUpgrade use a special .travis.yml file. Maybe this is really fixed...

**Pull request merged**
