### PR TITLE
[REF] travis_install_nightly: Install webkit patched

### PR DESCRIPTION
**Pull request by moylop260**
Help to fix projects where is required to test with webkit (wkhtmltopdf) patched.
https://github.com/OCA/reporting-engine/pull/86#issuecomment-265598246

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Will Odoo use this one?

**Comment by moylop260** [comment]
Yes, odoo program will use this one because we are affecting the `PATH` environment variable in the first line of `script` section from `.travis.yml` file.

**Comment by pedrobaeza** [comment]
OK, thanks! Travis status is the usual problem?

**Comment by moylop260** [comment]
> @hbrunn I personally would have made this an unreadable one liner using --strip-components=2 wkhtmltox/bin/wkhtmltopdf added to the tar command

This command is not supported with `-C` parameters but using a sub-command with `(sub-command)` we can use `cd` plus `strip-components`
Please, check last commit.

**Comment by moylop260** [comment]
> @pedrobaeza OK, thanks! Travis status is the usual problem?

Yes, the build 1 has the output:
[Done. Your build exited with 0.](https://travis-ci.org/OCA/maintainer-quality-tools/jobs/190328443#L590)

**Comment by hbrunn** [comment]
hey, this was really only meant as nitpicking :-)
will merge as red travis seems explained

**Comment by hbrunn** [comment]
oh no! my counting was: 2 + my own approval makes 3, so I can fast track... revert for sake of principle or can we let it slip if nothing horrible happens during the rebuild I just triggered?

**Comment by hbrunn** [comment]
breaks nothing and makes my tests work: https://travis-ci.org/OCA/reporting-engine/jobs/183578337 https://travis-ci.org/OCA/reporting-engine/builds/183578334
letting the rule violation slip this time would have my vote

**Comment by pedrobaeza** [comment]
With confident commiters/reviewers like our three involved is absurd to let 5 working days to pass for merging this, so no problem on my side.

**Pull request merged**
