### PR TITLE
[IMP] improve test_flake8 to ignore uninstallable modules

### PR DESCRIPTION
**Pull request by sbidoul**

### CODE REVIEW

**Comment by yvaucher** [comment]
:+1:

**Comment by lmignon** [comment]
:+1:

**Comment by max3903** [comment]
:+1:

**Comment by pedrobaeza** [comment]
Pylint is still checking unported modules: https://travis-ci.org/OCA/product-attribute/jobs/85247279

**Comment by sbidoul** [comment]
Hmm. It seems product_extended has no `__openerp__.py`. That must be the issue.

**Comment by pedrobaeza** [comment]
OK, I see, that could be solved then removing that module (as the vast majority of unported that will be finally removed...) or creating a manifest.

**Pull request merged**
