### PR TITLE
[REF] maintainer-quality-tools: Use eslint instead of jshint for javascript lints

### PR DESCRIPTION
**Pull request by moylop260**
More info: https://github.com/OCA/pylint-odoo/pull/97

- Fix exit early if you want test both: `LINT_CHECK="1" TESTS="1"`

TODO:
- [x] Update this branch after merge the CI fixes: https://github.com/OCA/maintainer-quality-tools/pull/390 to get a green
- [ ] Create other PR to update expected errors after merge this one and https://github.com/OCA/pylint-odoo/pull/97

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Where is the .jslintrc file?

**Comment by moylop260** [comment]
Oh yeah, you are right!
The file here is missing, by default will be used from `pylint-odoo`
If we need change a particular check for MQT we can think in change the default file or add a custom here.

**Comment by pedrobaeza** [comment]
OK, I would prefer to bundle here one for being less obscure than in the python library, but it's nothing critical.

**Comment by lasley** [comment]
> I would prefer to bundle here one for being less obscure than in the python library,

I like this too, but how would we maintain sync between the two if we did do this?

**Comment by pedrobaeza** [comment]
pylint_odoo maybe shouldn't include any sample configuration file.

**Comment by lasley** [comment]
I admittedly didn't know it did until this conversation came up, so I think that's probably a good call. Keep all the sample files centralized here, which is also part of our builds so is included there in case we also want to use them as defaults.

The flipside is that we're making `pylint_odoo` dependent on MQT in a way, right?

**Comment by pedrobaeza** [comment]
The only downside I see is that pylint_odoo can be self-checked unless you hardcode a configuration in the test.

**Comment by moylop260** [comment]
Team
FYI we have all approves to merge https://github.com/OCA/pylint-odoo/pull/97
But we need merge this PR together to work without errors.

But we don't have approves here.
Tell me what I should change to receive your approval or give me your approval to enjoy this feature, please.

**Comment by moylop260** [comment]
The approved https://github.com/OCA/pylint-odoo/pull/97 require this PR then I'll merge both but we will work changes about in other ones

**Pull request merged**
