### PR TITLE
WIP [REF] unbrand (travis)

### PR DESCRIPTION
**Pull request by blaggacao**
Signed-off-by: David Arnold <dar@devco.co>

This is maybe the first step: Simple renaming. Let's see how things break... 😄

### CODE REVIEW

**Comment by blaggacao** [comment]
I'm sorry, I'm a little bit lost, can anyone help me with the failing https://travis-ci.org/OCA/maintainer-quality-tools/jobs/172597066 and https://travis-ci.org/OCA/maintainer-quality-tools/jobs/172597067 having seen previous checks beeing socessfull while introducing only a minimal change meant for backwards compatibilityby the last commit.

**Comment by jcdrubay** [comment]
When executing the script maintainers-quality-tools>git>pre-commit, an unexpected unsuccessful check occurred.

I am in a similar situation as you trying to debug the travis failed tests. What I am doing is reproduce locally so I can debug. I am sharing with you hoping this can help you and maybe you can give me some tricks to go faster. Also, I believe that some documentations could be prepared for people who will be in our situation in the future.

You can try to run locally the 3 pre-commits checks to find out which one failed:
https://github.com/OCA/maintainer-quality-tools/pull/380/files#diff-41534b470a0a330c9c125702b9967f11

# Reproduce the problem locally

### Prepare your code
#### Assuming current folder is maintainers-quality-tools
cd /opt/openerp/code/github-trobz/maintainer-quality-tools

#### Prepare / reset
TEST_DIR=~/tests
export PATH=$TEST_DIR/maintainer-quality-tools/travis:$PATH

cd /opt/openerp/code/github-trobz/maintainer-quality-tools
rm -rf $TEST_DIR  # in case you already had it and want to reset
mkdir $TEST_DIR
cp -rf ../maintainer-quality-tools/ $TEST_DIR
cd $TEST_DIR/maintainer-quality-tools
cp -r tests/test_repo/* .
git add --all

### Clean environment variable:
unset EXCLUDE
unset INCLUDE
unset INSTALL_OPTIONS
unset INSTANCE_ALIVE
unset LINT_CHECK
unset OPTIONS
unset PYLINT_EXPECTED_ERRORS
unset RUN_COMMAND_MQT_CREATE_FOLDER
unset SERVER_EXPECTED_ERRORS
unset TRAVIS_PULL_REQUEST
unset TESTS
unset VERSION 

### Set global environment variable
export VERSION="9.0" TESTS="1" LINT_CHECK="0" TRAVIS_BUILD_DIR=$TEST_DIR/maintainer-quality-tools

### Set job specific environment variables (use the Clean environment variable above between 2 jobs )
#### env-test-case:matrix ==> 7
export VERSION=master EXCLUDE="broken_no_access_rule" LINT_CHECK="1" TESTS="0" PYLINT_EXPECTED_ERRORS="26" TRAVIS_PULL_REQUEST="true"  # Use PR pylint config file
#### env-test-case:matrix ==> 8
export VERSION="7.0" LINT_CHECK="1" TESTS="0" PYLINT_EXPECTED_ERRORS="24" TRAVIS_PULL_REQUEST="true"

### Travis tests can be executed with
./travis/travis_run_tests 8.0
./travis/self_tests

### Test the commit
Check variables values in this part of code from `self_tests`:
```
    if os.environ.get('TRAVIS_PULL_REQUEST', 'false') != 'false':
        git_script_path = os.path.join(os.path.dirname(
            os.path.dirname(os.path.realpath(__file__))), 'git')
        pre_commit_returned = subprocess.call(os.path.join(
            git_script_path, 'pre-commit'))
```

**Comment by blaggacao** [comment]
I guess, there must be a shortcut through the editor (in my case ST3). Like the `on_save()`, I already have for pep8. Ideally you would be aware not only at `pre-commiting`, but already at the `moment of typing`.

**Comment by moylop260** [comment]
FYI If you use docker you could use `travisfile2dockerfile https://github.com/oca/maintainer-quality-tools.git master` and build the expected build.

Yes, use a unbrand (something) is better

**Comment by blaggacao** [comment]
@moylop260 thanks, I also remember our hangout a year ago about this. We are actually using gitlab-ci, as it is perfectly integrated with the whole development workflow, from artifact management up to deployment triggers. Something, that travis cannot offer at this level, and less for free... 😉 
I guess in 4 years from now, we will be all working with gitlab in the Odoo community....

**Comment by moylop260** [comment]
I use gitlab too.
Using t2d you can use any CI really 😃 (you can see that runbot community now works with t2d too)

I mentioned t2d because I understood that there is a error in travis that can't reproduce it locally and t2d could be useful for reproduce it and fix it (unrelated with a particular CI)

**Pull request closed without merging**
