### PR TITLE
[REF] pylint_run: Use of pylint_odoo instead of deprecated pylint_oca

### PR DESCRIPTION
**Pull request by moylop260**
- Use new pylint_odoo package fix OCA/maintainer-quality-tools#268
 - Install `pylint_odoo` packages only is necessary.

### CODE REVIEW

**Comment by moylop260** [comment]
FYI coverage without github statuses reported but build here https://coveralls.io/builds/3822639 with `coverage increased (+0.4%) to 88.11%`

**Comment by pedrobaeza** [comment]
You comments:

* As you're modifying travis_install_nightly, why don't you convert it to Python to expand possible contributors that knows better this language?
* Can you exclude the download and decompression of odoo on Transifex pull requests (but not on builds)?

**Comment by moylop260** [comment]
@pedrobaeza 
Thanks for you comment

> As you're modifying travis_install_nightly, why don't you convert it to Python to expand possible contributors that knows better this language?

I'm working in PR as short as posilbe to avoid the past error of big pr or multi-goal pr's
IMHO a python migration of `travis_install_nightly` is offtopic from feature to use `pylint_odoo`

> Can you exclude the download and decompression of odoo on Transifex pull requests (but not on builds)?
Same case.

I can help you to create a new issue for these goals.

**Comment by moylop260** [comment]
@pedrobaeza 
FYI https://github.com/OCA/maintainer-quality-tools/issues/272 and https://github.com/OCA/maintainer-quality-tools/issues/271

**Comment by pedrobaeza** [comment]
:+1:

**Comment by dreispt** [comment]
:+1:

**Comment by oscarolar** [comment]
:+1:

**Comment by moylop260** [comment]
Can be merged?

**Comment by pedrobaeza** [comment]
I'm waiting the mass-commit tests end to not interfere in that process.

**Comment by moylop260** [comment]
@pedrobaeza 
Is mass-commit process finished?

**Comment by pedrobaeza** [comment]
Yeah, it is. I merge.

**Pull request merged**
