### PR TITLE
[IMP] pip install requirements

### PR DESCRIPTION
**Pull request by mathi123**
this fixes my install bugs for odoo + .NET build with mono, on 1 system
e.g. [see here](https://travis-ci.org/mathi123/dotnet/builds/68430398)

### CODE REVIEW

**Comment by max3903** [comment]
:+1:

**Comment by pedrobaeza** [comment]
:+1:

**Comment by bwrsandman** [comment]
Can you squash your 4 commits

**Comment by dreispt** [comment]
Yes, could you squash the commits please.

**Comment by mathi123** [comment]
I screwed this up, closing..

**Pull request closed without merging**
