### PR TITLE
[FIX] set pillow version in travis requirements, version 8.0 PR are failling

### PR DESCRIPTION
**Pull request by oihane**
take a look to https://github.com/OCA/sale-workflow/pull/388

### CODE REVIEW

**Comment by oihane** [comment]
This PR has the same travis error as master branch, can anyone take a look...

**Comment by mikelarre** [comment]
:+1:

**Comment by anajuaristi** [comment]
:+1:

**Comment by oihane** [comment]
@dreispt @moylop260 can you please take a look?

**Comment by moylop260** [comment]
The red build is unrelated the merging

**Comment by dreispt** [comment]
@moylop260 we really need to do something regarding these false red builds. I prefer the dysfunctional tests to be disabled until the underlying issue is fixed.

**Comment by moylop260** [comment]
Are you talking about https://github.com/travis-ci/travis-ci/issues/6861#issuecomment-262255906?

**Pull request merged**
