### PR TITLE
[REF] pylint_pr.cfg: Enable po checks

### PR DESCRIPTION
**Pull request by moylop260**
Enable pylint-odoo checks: duplicate-po-message-definition, po-msgstr-variables and po-syntax-error
In order to detect PO files errors early

More info about these checks:
 - https://github.com/OCA/pylint-odoo/pull/290

It is enabled as beta so won't affect build status

### CODE REVIEW

**Comment by moylop260** [comment]
@pedrobaeza @sbidoul @dreispt 
Could you check it, please?

**Comment by pedrobaeza** [comment]
We should enable them as well in pre-commit for 13.0

**Comment by sbidoul** [comment]
> We should enable them as well in pre-commit for 13.0

Agreed, this should be done in https://github.com/OCA/oca-addons-repo-template

**Comment by moylop260** [comment]
So, Can we merge it?

**Pull request merged**
