### PR TITLE
Add pylint-odoo dependency, used for pylint checks

### LINKED ISSUE #356: ImportError: No module named click
If you try to run `travis/run_pylint.py`

### PR DESCRIPTION
**Pull request by dreispt**
Fixes #356

### CODE REVIEW

**Comment by moylop260** [comment]
For me is a good idea have lxml and pylint-odoo in requirements.txt for get all dependencies in local cases but we know that is slow use it for travis.

Could you add a sed to delete from requirements.txt the pylint-odoo
https://github.com/OCA/maintainer-quality-tools/blob/master/travis/travis_install_nightly#L10?

If you compare the time waste for this pr vs stable one you will a increase.

**Comment by moylop260** [comment]
Other reason to add the sed is that we have separated the environments of lint and test
Then we dont need have pylint-odoo for test build and we dont need install all dependencies of test for lint one

**Comment by dreispt** [comment]
@moylop260 sorry, I didn't understand - you dislike the PR?

**Comment by moylop260** [comment]
I like the pr but plus a change.
We need faster builds.

Then you need add a sed command to delete the line added.

I mean, the requirements.txt for install test dont should have `pylint-odoo` then remove it with a sed command.

IMHO a full requirements is for local matter. Rigth?

**Comment by dreispt** [comment]
@moylop260 Is the delay added significant?
If so, how about adding a `requirements-lint.txt` file instead. Builds could install it when in case the LINT flag is activated.

**Comment by moylop260** [comment]
I like `requirements-lint.txt` for add flake8 and pylint-odoo

**Comment by dreispt** [comment]
@moylop260 Travis builds are able to run without installing `pylint-odoo`?

**Comment by lasley** [comment]
@dreispt The tests are, yeah. Pylint is only required for LINT=1 IIRC

**Comment by dreispt** [comment]
Close?

**Comment by nhomar** [comment]
I just update the PR to be mergeabele, is this valid yet @moylop260 ¿?

**Comment by moylop260** [comment]
pylint needs hacks to install for travis, because we dont want lxml installable from pip requirements and we dont need it for no lints builds

**Pull request closed without merging**
