### PR TITLE
[REF] Allow to specify a specific directory for lint tests

### PR DESCRIPTION
**Pull request by yvaucher**
As a first step to integrate the use of MQT with build with anybox buildout recipe here I allow to configure pep8 and lint directory to check.

### CODE REVIEW

**Comment by yvaucher** [comment]
@moylop260 I'm not sure if it was how you planned to use the --path argument, however it feels more convenient to have a single env var for both flakes8 and pylint without altering TRAVIS_BUILD_DIR.

Your review is welcome

**Comment by guewen** [comment]
:+1:

**Comment by pedrobaeza** [comment]
:+1:

**Comment by lmignon** [comment]
:+1:  @yvaucher I'm curious/interested to see how you'll integrate MQT with buildout....

**Comment by yvaucher** [comment]
@lmignon This is WIP I might come up with something at the end of day.

**Comment by moylop260** [comment]
LGTM
I will to change my progressive PR to have this change.
Thank you

**Comment by dreispt** [comment]
It would be nice to have this feature documented somewhere.

**Comment by dreispt** [comment]
Took another look at the code, and I like the idea of MQT being compatible but getting away from being a TravisCI specific tools. 
MQT should become a test build tool that also works in TravisCI, and this is a step in that direction.

**Comment by yvaucher** [comment]
@dreispt Where would it be better to document this? I'm not sure all ENV VAR are documented properly

**Comment by pedrobaeza** [comment]
This needs a rebase

**Comment by guewen** [comment]
@yvaucher could you rebase?

**Comment by yvaucher** [comment]
@guewen rebased

**Comment by guewen** [comment]
Travis is not happy with this `click` thing:

```
Traceback (most recent call last):
  File "/home/travis/build/OCA/maintainer-quality-tools/git/test_pylint", line 165, in <module>
    ] + extra_params_cmd, standalone_mode=False)
  File "/home/travis/virtualenv/python2.7_with_system_site_packages/local/lib/python2.7/site-packages/click/core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "/home/travis/virtualenv/python2.7_with_system_site_packages/local/lib/python2.7/site-packages/click/core.py", line 679, in main
    with self.make_context(prog_name, args, **extra) as ctx:
  File "/home/travis/virtualenv/python2.7_with_system_site_packages/local/lib/python2.7/site-packages/click/core.py", line 594, in make_context
    self.parse_args(ctx, args)
  File "/home/travis/virtualenv/python2.7_with_system_site_packages/local/lib/python2.7/site-packages/click/core.py", line 858, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
  File "/home/travis/virtualenv/python2.7_with_system_site_packages/local/lib/python2.7/site-packages/click/core.py", line 1354, in handle_parse_result
    value = self.full_process_value(ctx, value)
  File "/home/travis/virtualenv/python2.7_with_system_site_packages/local/lib/python2.7/site-packages/click/core.py", line 1636, in full_process_value
    return Parameter.full_process_value(self, ctx, value)
  File "/home/travis/virtualenv/python2.7_with_system_site_packages/local/lib/python2.7/site-packages/click/core.py", line 1329, in full_process_value
    raise MissingParameter(ctx=ctx, param=self)
click.exceptions.MissingParameter: None
pylint_status=$?
exit $((${status1} || ${status2} || ${pylint_status}))
Traceback (most recent call last):
  File "./travis/self_tests", line 71, in <module>
    "Git pre-commit script returned value != 0"
AssertionError: Git pre-commit script returned value != 0
```

**Comment by dreispt** [comment]
We need to figure why some builds are failing.

**Comment by pedrobaeza** [comment]
I close this old one as there hasn't been updates.

**Pull request closed without merging**
