### PR TITLE
Add automatic merge integration of proposed satellite repos

### PR DESCRIPTION
**Pull request by dreispt**
Contains #337

### CODE REVIEW

**Comment by moylop260** [comment]
Sorry, I don't understand this change.
Do you have a documentation to read it or a real example?

**Comment by sbidoul** [comment]
@dreispt I'm all in favor of smaller repos. But I don't understand this PR. Is it to merge the small repo in the big one automatically?

**Comment by pedrobaeza** [comment]
I close this one until we have clearer how to implement this.

**Comment by dreispt** [comment]
@sbidoul The point is to allow to run integration tests of modules from different repos.
Example: from OCA/project we created spin-off repos OCA/project-gtd and OCA/project-service.
But we want these repos to run installation and Python tests together.
So, for example, "OCA/project" could be told to get the modules from OCA/project-gtd and OCA/project-service and run the tests on all three on the same build.

This way, an "integration repo" is able to oversee what is going on on their satellite repos.
Does this make sense?

**Comment by sbidoul** [comment]
@dreispt yes I see the need for integration testing. Thanks for the clarification.

**Comment by dreispt** [comment]
@sbidoul Good. I was afraid it could be far fetched 😄  
This mechanism could also be used for an eventual OCX to be tested along with some (or all) OCA addons.

**Comment by sbidoul** [comment]
@dreispt maybe we don't need a full fledged repo to do integration testing. Perhaps a simple requirements files of addons to be tested together could be sufficient.

**Pull request closed without merging**
