### PR TITLE
[REF] pylint: Enable check to validate CamelCase class name for odoo version >= 8.0

### PR DESCRIPTION
**Pull request by moylop260**
> Progressive PR from https://github.com/OCA/maintainer-quality-tools/pull/232
To review the real diff of this PR see last commit.

This PR enable check to validate CamelCase class name just for modules changed and just for modules of odoo version >= 8.0

### CODE REVIEW

**Comment by pedrobaeza** [comment]
You don't need to depends on https://github.com/vauxoo-dev/maintainer-quality-tools/commit/ed542ce2d0d138b333dad5d57dd30473291064c3 for this one, doesn't it?

**Comment by moylop260** [comment]
@pedrobaeza 
I need it because this is a new conventions

**Comment by nhomar** [comment]
2015-08-18 12:58 GMT-05:00 moylop260 <notifications@github.com>:

> I need it because this is a new conventions


@pedrobaeza.

1. Have the script does not mean we will run it all at once without take
care.
2. You need to decide, if we will have the rule we ned automate it, it is
more risky continue expending this job manually to all collaborators as I
exposed before.
3. We already test them in our repositories and we passed some iterations
already.

Then block this PR just becuase a non fundamented fear is not correct.

- It has unit tests to vaildate regresions.
- If I have a repository which call a class with wrong names will be red
BEFORE the PR is excecuted, and ALL the manual checks that we are doing
will be done automatically....
- The miogration is manual we are only giving a tool, not automating the
conversion itself...

What is exactly the situations where you think it can fails in order to
include such unit tests and considere in the code?

BUt a Generic "too dangerous" is not a good and productive incentive
here.... con you please be more precise?





-- 
--------------------
Saludos Cordiales

CEO at Vauxoo <https://www.vauxoo.com> Odoo's Gold Partner.

[image: --]
Nhomar Hernandez
[image: http://]about.me/nhomar
<http://about.me/nhomar?promo=email_sig>

**Comment by pedrobaeza** [comment]
OK, I understand. Let's follow this path then.

**Comment by dreispt** [comment]
This depends on #232 and most of the code is already there. instead of "Needs Review" It would be better marked as "WIP" (though it would be nice t have a tag for "Wainting on Dependencies"...).

**Comment by moylop260** [comment]
I [promised](https://github.com/OCA/maintainer-quality-tools/pull/232#issuecomment-137435807) to @lepistone  add message clearer.
This PR check CamelCase but just show `invalid-name`

Now, with next PR https://github.com/OCA/maintainer-quality-tools/pull/234 we have next message:
`Use CamelCase "%s" in class name "%s". You can use oca-autopep8 of https://github.com/OCA/maintainer-tools to auto fix it.`

Then I close without merge this one.

**Pull request closed without merging**
